### ISSUE TITLE
Is FFMPeg the new home for libutvideo?

### ISSUE THREAD

**Issue by timofonic** [qyot27/libutvideo#10]
Hello.

@qyot27 
@cehoyos 
@dwbuiten
@eddiehao
Can this repository be considered superseeded by FFMpeg one? It seems it's merged into FFMPeg.

https://github.com/FFmpeg/FFmpeg/commit/593bb50e062fae474880f5ab353fec9f751dc06e

https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideoenc.cpp
https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideodec.cpp
https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideo.h

Was this solved?
https://trac.ffmpeg.org/ticket/3651

Kind regards.

**Comment by cehoyos** [comment]
Hi!

On Sun, 14 Feb 2016, Timofonic wrote:

> Can this repository be considered superseeded by FFMpeg one? It seems 
> it's merged into FFMPeg.

No, it will not be merged into FFmpeg.

> FFmpeg/FFmpeg@593bb50
> 
> https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideoenc.cpp
> https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideodec.cpp
> https://github.com/FFmpeg/FFmpeg/commits/master/libavcodec/libutvideo.h

> Was this solved?
> https://trac.ffmpeg.org/ticket/3651

No, why do you think so? The ticket is still open.

Carl Eugen

**Comment by qyot27** [comment]
>Can this repository be considered superseeded by FFMpeg one? It seems it's merged into FFMPeg.

Those files have absolutely nothing to do with libutvideo being 'merged' anywhere.  Those are just a wrapper that lets FFmpeg link to libutvideo.
