### ISSUE TITLE
GNUC mode compile errors

### ISSUE THREAD

**Issue by csghone** [qyot27/libutvideo#5]
In file CPUID.h, in following functions "res" is used instead of "result" for if defined(__GNUC__)
static inline void cpuid 
static inline void xgetbv

**Comment by qyot27** [comment]
Fixed in https://github.com/qyot27/libutvideo/commit/161fb016c0cb037ff4f18a18f7a2966b665a2bc1

The issue is that it wasn't adjusted in upstream, likely because upstream dropped GCC support some time ago and this is an artifact of that.

**Comment by csghone** [comment]
Thanks for the update!
